# Generated by Django 5.1.1 on 2024-09-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoSignals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccuknoxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
    ]
